package be.eafcuccle.tshirtshop.models;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * The Brand entity represents a brand in the T-shirt shop application.
 * Each brand has a unique name and is associated with a collection of products.
 */
@Entity
@Table(name = "brand")
public class Brand {

    /**
     * The unique identifier for each brand, auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    /**
     * The name of the brand. It must be unique and cannot be null or blank.
     */
    @NotBlank(message = "The brand name cannot be empty")
    @Column(unique = true, nullable = false)
    private String name;

    /**
     * The list of products associated with the brand.
     * When a brand is deleted, its associated products are also deleted.
     */
    @OneToMany(mappedBy = "brand", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<Product> products = new ArrayList<>();

    /**
     * Default constructor for JPA.
     */
    public Brand() {}

    /**
     * Constructs a Brand with the specified name.
     *
     * @param name the name of the brand
     */
    public Brand(String name) {
        this.name = name;
    }

    /**
     * Returns the unique identifier of the brand.
     *
     * @return the brand's ID
     */
    public Integer getId() {
        return id;
    }

    /**
     * Sets the unique identifier of the brand.
     *
     * @param id the brand's ID
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Returns the name of the brand.
     *
     * @return the brand name
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the name of the brand.
     *
     * @param name the brand name
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Returns the list of products associated with this brand.
     *
     * @return a list of products
     */
    public List<Product> getProducts() {
        return products;
    }

    /**
     * Checks if this brand is equal to another object.
     * Brands are considered equal if they have the same ID.
     *
     * @param o the object to compare with
     * @return true if the objects are equal, false otherwise
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Brand)) return false;
        return id.equals(((Brand) o).id);
    }

    /**
     * Returns the hash code of the brand, based on its ID.
     *
     * @return the hash code
     */
    @Override
    public int hashCode() {
        return Objects.hash(id);
    }

    /**
     * Returns a string representation of the brand.
     *
     * @return a string representation of the brand
     */
    @Override
    public String toString() {
        return "Brand{id=" + id + ", name='" + name + "'}";
    }
}
